sudo: required
language: node_js  # since we are building the prod bundle in travis
node_js:
  - "9.4.0"
services:
  # we need docker to run the tests; NOTE: tests are run against dev env
  - docker
env:
  # add secure environment variables
  global:
  - secure: anKSkkpOGUT4q0PQgJcwVfX1DT37lfXrGA1XNCFBSqTjdlICIwedYIeU87k20t+Fg4ZuYBXwwhvozByFOOkG5JDQ6yFkeuJJBWExfNtR6U/EokB6oO6wVWiqi6YpqF1aI9QojYVN5k5NL1niDRhH2N3M5YhFrCv4JasBIrQ8Z3UD8ou4cauOt7FylA5WCyS2bBM4tSfBOYR5Vsen4rKMqJZDTqIMZpQS3oh74lT/N5u3ClFNw5DBwAgixzfL4um8eE38SxsffDCqZqgbu/9L+2+oHF9C/4Gc5oawnJopxFVUq9ZhgONmjIJPUK7PJHyF1es+AZTjIvEJMDmuFesw+gWz7tEKpsHug/syJZOYZlQtsu3ZyLYiDub8/ug1tBhUpsjJsWtOxRLj2uqDqCoKYC3XccwGkjc0GdIjuTFSnhekZHmkXFd+zpCjJuYIAsx6cym2ig0Hwl+X0h4MtM4DEDKKJ4BbJeb1IlPGmRYlz+t5QIe5sG87DHrTftFjBxb5A/EknhAoAWDuzUbsSHTVAgNs3OPJf21RGPTD2R0MMOiD6/hd7QKJsNNsxwAaoqPs1D9Mdn9oRxyTPdCJdORwJ9lhf+YXbwBZLSSpMcH631JQrszgAZj7uoNODLSAWHBTlp0QUArh1ELP1bMZ1Z2ifMAsT7Bo4h1CTbCtVVt24+8=
  - secure: TMduu41/AuBmvT9c1zQT9cOIsFP4CnLOG6iC/kseXZxDUuSHNk+0kwgwGpRGg4fKTWOUPS83fC5wyl16CiqHlhViRbSkyV5ujTlmM2g5IIDbWX7Z7+vJRULXre8Ow7vsa12e4T4FOY1WsriFq26Xh0jqVGl1bsUu+lkFccxAjJSNisifanyDEjsNo/A4ci2PA/BuzO+KsoUof6XwozF8Xg84LCWHOFIP8aEmGNJe5KSshkQPK5xA3T0uszdt3O5eq2anjhSpTUHopeRjFu7uAy69ll7E9HjxmECfCJZT5iHs75icWrVZrat9upww+3ciEjBGyiz+47fXN2gdq7JLgLxTsgeDMQ44KW4TjTmqIarqMIM9qnU5UeVrmvmF/dFOFWSWX9oT2nRntfsawIp/E8dgdsPNXSP3l6DoMGK6gZyT6nTCLs69kmPV9vU5ojY4DBYI4VjbW8X5TqfkJTUxFGj/LUgaLGAAzlJNeji7aUQ43+zG4bYOHn8e6s2mBZCYq5RPpfiOHOV92rHNxP5aFhZXUmJEoaS2T80TUhocvWE1mH6ctCera6E3miSVGdeK9xJgA8caXsaLfrKWyVd19JppsnM+B0ZwQU6WTj/KcaaOYYG6uOgdyGm3Sjg+ugjufdcyLwz6A4g3ltLLyifAA7PwUaNU3sAxHuwfv85ULJo=
  - secure: K9IZGT2hrKb/6Ygt1oRbiLKCTWD2Hdp7VHAB5RjaoC9xxWG4kRsnCE5OqKGFUWIEAXozYzZUnaDyTHuupVjZjHlMxA71VXuwl1B1/0MD9F+8fJ6h4D9GuXr+7MBI8o2OTdpSjl1fPHSFTJ1il2dpwIq1GNBwFIKFd7djpi3BWCaFQUaCfIP5P0OFIkAv+9MY98iT92URNvI29dIPH3LIGlA2RCsQuCGMW7qJmOPQ2JNZuWMqZ+B2tphXBmBdtRaEJAZgMFc0vkP/rB3e17DfastFfJVfCO/DK3Z5+q9ltkFSpa5gRutOVOHsyJJLWKVdz1CukT85RwBvB4X89+Tvl0cmOCLHto3VpvCdAaal7B8tYAhMdvLH03Y1MTwCBqB1gim45N0iEYnbYJsor3x0MzdUaKL7AlzYLgG+rJ8Ly62FY6W1ypVwRh+zxMlpnCiarSeFboh25BJGBKneMPG1NeT96GKV+JDHEiLnfzbjIi6FWpV6w9Vg/iN62Za+l0fWDeYJtaSr89JEnOFVvjKL9FTQ3jKkUUOqqFm0+OVAgkYnmPYzZSRUWiLIkw3wfW6C4o5NJvM/lWvywoBOmZb9IMJ09H3uXsL2KyZzEP9uN/46O4abUQJHNJgu6F/uPI7elK9gU+ILPUPn8ppqL2mzpwR9ZaEv27hwNEFb6EmVbHk=
  - secure: IXPGKCDyHy0FDl9MS/5iDeSnAyje6aABR2NId0yIy5DTS9vAKmSSV6Ogm9tglvwnfGLa0ZMHlIe4oitjNf/GLE0AqI1cohzESIswhfsDSrLb2nf9xnuaJH0fUOPrpd4ZkFx265n57J0BY+SUXy/4L2lwGQ68fTxjC/4u2za9L730/XbHqPr8Z9OCRcJRMwozO9S377aszfPWYmvVSz0c+CcdzAZJpvt7Wc/aFDktjLODXC6zhzehlaHXLN2dh4Kv2FVXqmtKl8TxRkwbUG7Eo67icYWReC7FUfLntW2b3WkzyHriG7Kv27Mj9AKUR5rNpElDihylZU1x0VJGW1O2ez/7zEAZco7vmJVBci2Tzbi1BCnnjkSd9Mv4urd1SsHCnQZ2+T5bgNs63Z2MZmQii0liCNpgx+FigCRb96OuRZVBFPWcssJZzrEjWXJgh+hXBzRDFm60LgFnAFwu/grVs8ySCgWLqxHG4bRCXgYpU7nGNSR3diXUpSU/8efAgfC6bWw1sTVolUELTVXzaX013MOc4gpeejuTuEBSBIeCTTRnYUQ8XppaIX8+L0n+A2rlLuSBNH1s/qhQm4HW6ZgYyOU78xaL3Y4etFAn8uYjgvUvobSPdD9C5AsQzS1ah5eMazjnbUb5MP1Ys1hw0BZjmv83GpKGHtJTumdFfizKEXE=
  - secure: tYZ4OKuvWhYLipoUzeCLNpP3nQO4v0gOd6TKMKaYlHa2OoB5AVAU2h3xWzjcoh/kfm0eM63FIu/u7qK0Hy1k2hQQfI/HUOG4RQDg8Qqv72UEAaSGIBhQT4p6JdMRHXdZDWbYcpilNQ423UZQPckcFSjXtt7mVE7cNOF50OarHGtx8zLxbbLydCweJxvO5YILg6c+3kWaQSQwHjj56+u2uDgRP/1OyCx44/Bep+h4xHriwpl/GeB2474NNVOKu0mDyX3KOcpAym1ppD8RJNYuqXbq+VQTOWf/IjSh1pyjD5mkeljBLpyEF47T58bqUvfsbo9B63fl2sPXo5+HZ6lekqKYvt18nDUvu8Oa0YokczaIZCsTBA+X97zgqCN8tCvYnpw0Z1jiqjjQofXQs0E57WwjoNWwfknxbaUvRR25K0Oo5A6v2SovH2D4YaaDTRbQ0oHV1umcbyWZcu66YsL4gaxJI5HsQZrlouVUi23anQ9VWutk8WMU91JgueXrysgV4zCbMnwechE4yhMK+Q1HeDIEMMGDgIOVvsnd6FoFyaKtDTE6jE+3CDgZCHn6YbT0gFBJqBOBEIRZrulCPUgsgPJ8L+oI3ru1LY9GQIQunvr57QK+uKs7Nij/FVfgOeMUYomORtNg23646gTzPSLrPIwBZ0m2Qb0MOJ3F5r5xW9g=
before_install:
  # decrypt all deploy key files
  - bash ci-scripts/decrypt-deploy-keys.sh
before_script:
  # spin up the dev docker containers
  - docker-compose up --build -d
script:
  # run the tests
  - "./test.sh"
after_script:
  # spin down the dev docker containers
  - docker-compose down
before_deploy:
  # build the application for prod
  - bash ci-scripts/build.sh
deploy:
  # deploy to prod
  provider: script
  script: bash ci-scripts/deploy.sh
  skip_cleanup: true  # do not clean working dir so we can push build code
  on:
    all_branches: true
  #   branch: master
