# dev docker-compose config

version: '2'
services:
  dev_server:
    env_file:
      - .env
      - .secrets
    environment:
      - DEV_ENV=true
    build:
      context: ./server/
    volumes:
      - ./server/:/go/src/github.com/connorwalsh/new-yorken-poesry-magazine/server
      - "${EXEC_MOUNT_DIR}:${EXEC_DIR}"
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.dev-data/poets:/poets
      - ./migrations:/migrations
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
      - xaqt
    links:
      - "db:${DB_HOST}"
      - "maildev:maildev"

  dev_client:
    env_file: .env
    build:
      context: ./client/
    command: npm start
    volumes:
      - ./client/:/client/
      - /client/node_modules
    ports:
      - "${CLIENT_PORT_DEV}:${CLIENT_PORT_DEV}"
    depends_on:
      - dev_server
    links:
      - "dev_server:${SERVER_HOST_DEV}"

  xaqt:
    env_file: .env
    image: "${XAQT_IMAGE}"

  db:
    env_file: .env
    build:
      context: ./db/
    environment:
      - DEV_ENV=true
    volumes:
      - ./.dev-data/db:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000

  # dev smtp server + mail gui
  maildev:
    image: djfarrelly/maildev
    ports:
      - 1080:80 # expose mail gui at 1080
