# production docker-compose configuration

version: '2'
services:
  nypm:
    env_file: .env
    image: "${DOCKER_IMAGE}"
    volumes:
      - "${EXEC_MOUNT_DIR}:${EXEC_DIR}"
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
      - xaqt
    links:
      - "db:${DB_HOST}"
    restart: always

  xaqt:
    env_file: .env
    image: "${XAQT_IMAGE}"

  db:
    env_file: .env
    image: postgres
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000
